apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    role: my-local-pv
spec:
  storageClassName: pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"