apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-live-claim
  labels:
    role: webook-mysql-live-claim
spec:
  storageClassName: pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  